
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.195.149:3306/api
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true